(fungsi(){var gtConstEvalStartTime = Tanggal baru();/*

 Hak Cipta Penutup Perpustakaan Penulis.
 SPDX-Lisensi-Identifier: Apache-2.0
*/
var h=this||self,l=/^[\w+/_-]+[=]{0,2}$/,m=null;function n(a){return(a=a.querySelector&&a.querySelector ("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&l.test(a)?a:""}fungsi p(a,b){fungsi c( ){}c.prototype=b.prototype;ai=b.prototype;a.prototype=new c;a.prototype.constructor=a;ah=function(g,f,k){for(var e=Array( argument.length-2),d=2;d<arguments.length;d++)e[d-2]=arguments[d];return b.prototype[f].apply(g,e)}}fungsi q( a){return a};fungsi r(a){if(Error.captureStackTrace)Error.captureStackTrace(this,r);else{var b=Error().stack;b&&(this.stack=b)}a&&( this.message=String(a))}p(r,Error);r.prototype.name="CustomError";fungsi u(a,b){a=a.split("%s");for(var c="",g=a.length-1,f=0;f<g;f++)c+=a[f]+(f<b.length?b[f]:"%s");r.panggilan(ini,c+a[g])}p(u,r);u.prototype.name="AssertionError";fungsi v(a,b){lempar u baru("Gagal"+(a?": "+a:""),Array.prototype.slice.call(argumen,1));};var w;fungsi x(a,b){this.g=b===y?a:""} x.prototype.toString=function(){return"TrustedResourceUrl{"+this.g+"}"};var y={};function z(a){var b=document.getElementsByTagName("head")[0] ;b||(b=document.body.parentNode.appendChild(document.createElement("head")));b.appendChild(a)}var y={};function z(a){var b=document.getElementsByTagName("head")[0];b||(b=document.body.parentNode.appendChild(document.createElement("head")) );b.appendChild(a)}var y={};function z(a){var b=document.getElementsByTagName("head")[0];b||(b=document.body.parentNode.appendChild(document.createElement("head")) );b.appendChild(a)}
function _loadJs(a){var b=document;var c="SCRIPT";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c); c.type="text/javascript";c.charset="UTF-8";if(void 0===w){b=null;var g=h.trustedTypes;if(g&&g.createPolicy){coba{ b=g.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(t){h.console&&h.console.error(t.message)}w=b}else w=b}a=(b=w)?b.createScriptURL(a):a;a=new x(a,y);a:{try{var f=c&&c.ownerDocument,k=f&&(f.defaultView ||f.parentWindow);k=k||h;
if(k.Element&&k.Location){var e=k;break a}}catch(t){}e=null}if(e&&"undefined"!=typeof e.HTMLScriptElement&&(!c||!(c instanceof e .HTMLScriptElement)&&(c instanceof e.Location||c instanceof e.Element))){e=typeof c;if("object"==e&&null!=c||"function"==e)try{var d =c.constructor.displayName||c.constructor.name||Object.prototype.toString.call(c)}catch(t){d="<objek tidak dapat dirangkai>"}else d=void 0== =c?"undefined":null===c?"null":typeof c;v("Argumen bukan %s (atau tiruan non-Elemen, non-Lokasi); mendapat: %s",
"HTMLScriptElement",d)}sebuah instance dari x&&a.constructor===x?d=ag:(d=typeof a,v("objek yang diharapkan dari jenis TrustedResourceUrl, mendapat '"+a+"' dari jenis "+("objek "!=d?d:a?Array.isArray(a)?"array":d:"null")),d="type_error:TrustedResourceUrl");c.src=d;(d=c.ownerDocument&&c. ownerDocument.defaultView)&&d!=h?d=n(d.document):(null===m&&(m=n(h.document)),d=m);d&&c.setAttribute("nonce",d) ;z(c)}
function _loadCss(a){var b=document.createElement("link");b.type="text/css";b.rel="stylesheet";b.charset="UTF-8";b.href= a;z(b)}fungsi _isNS(a){a=a.split(".");for(var b=window,c=0;c<a.length;++c)if(!(b =b[a[c]]))return!1;return!0}fungsi _setupNS(a){a=a.split(".");for(var b=window,c=0;c<a. panjang;++c)b.hasOwnProperty?b.hasOwnProperty(a[c])?b=b[a[c]]:b=b[a[c]]={}:b=b[a[c ]]||(b[a[c]]={});kembalikan b}
window.addEventListener&&"undefined"==typeof document.readyState&&window.addEventListener("DOMContentLoaded",function(){document.readyState="complete"},!1);
if (_isNS('google.translate.Element')){return}(function(){var c=_setupNS('google.translate._const');c._cest = gtConstEvalStartTime;gtConstEvalStartTime = undefined;c._cl=' id';c._cuc='googleTranslateElementInit';c._cac='';c._cam='';c._ctkk='447223.766484856';var h='translate.googleapis.com';var s=(true? 'https':window.location.protocol=='https:'?'https':'http')+'://';var b=s+h;c._pah=h;c._pas=s; c._pbi=b+'/translate_static/img/te_bk.gif';c._pci=b+'/translate_static/img/te_ctrl3.gif';c._pli=b+'/translate_static/img/loading.gif';c. _plla=h+'/translate_a/l';c._pmi=b+'/translate_static/img/mini_google.png';c._ps=b+'/translate_static/css/translateelement.css';c._puh='translate.google .com';_loadCss(c._ps);_loadJs(b+'/translate_static/js/element/main_id.js');})();})();